### ISSUE TITLE
Dark theme? 

### ISSUE THREAD

**Issue by zombodotcom** [RyanFitzgerald/devblog#16]
I saw you had `import 'prismjs/themes/prism.css';`

https://github.com/PrismJS/prism-themes

There's some good dark themes in there, I just don't know how to implement it with your build

**Comment by RyanFitzgerald** [comment]
In order to change the prism theme, you should be able to just import the required stylesheet. So instead of `import 'prismjs/themes/prism.css';`, you would use `import 'prismjs/themes/prism-<whatever-theme>.css';`. For example, to use the CB theme listed in the link you provided, you'd use `import 'prismjs/themes/prism-cb.css';`. 

Hope that helps. Let me know if you run into any other issues.
